---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-confirmation:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "a90deee7-6f87-4b73-b87d-b4864440bfff"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "404":
          content:
            application/json: {}
