---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-working-instruction:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "c878bd12-b345-4b71-9771-78d193c55cff"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "204":
          content:
            ? ""
            : {}
