---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-working-instruction:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "832f852e-e1ce-45bd-bcb8-1bc80a13fa65"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "404":
          content:
            application/json: {}
