---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /tasks/{USER_ID}/{TASK_TYPE}:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "8d7d0ce7-db78-4c8e-84b3-883cb1715c12"
      - name: "TASK_TYPE"
        in: "path"
        required: true
        example: "quality_inspection_operation"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "200":
          content:
            application/json: {}
