---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-scan-data-matrix:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "42522358-d8bc-4054-a8ac-bf15014ef20a"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "204":
          content:
            ? ""
            : {}
