---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /tasks/{USER_ID}/{TASK_TYPE}:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "83e8cb11-4bf9-4d16-b840-b42ec08cb0c7"
      - name: "TASK_TYPE"
        in: "path"
        required: true
        example: "confirmation_operation"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "200":
          content:
            application/json: {}
