---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}:
    get:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "ab7a3b96-bb4b-44c2-9a76-e73913a0a453"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json: {}
