---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-scan-data-matrix:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "6a0163be-1355-468f-8d28-6d9ac4619fd0"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "204":
          content:
            ? ""
            : {}
