---
openapi: "3.0.1"
servers:
- url: "blackboard.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /cleanData:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            text/plain; charset=UTF-8: {}
