---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /dev/users/{USER_ID}:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "35ccc80c-1d33-4fc9-9ea4-55fecca3cced"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "200":
          content:
            application/json: {}
