---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}:
    get:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "72c23e72-8ace-49ae-9bb9-b758ec9c95b5"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json: {}
