---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-confirmation:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "0c8d9f30-6c77-4e01-80ef-891720724547"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "204":
          content:
            ? ""
            : {}
