---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}:
    get:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "88245b5e-83ef-4322-b691-d1d9c738a3ca"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json: {}
