---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /tasks/{USER_ID}/{TASK_TYPE}:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "280f0ee9-d9db-4b56-8c12-45fd6c200c68"
      - name: "TASK_TYPE"
        in: "path"
        required: true
        example: "quality_confirmation_operation"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "200":
          content:
            application/json: {}
