---
openapi: "3.0.1"
servers:
- url: "mas.kursakov.dev1.cluster.robo.arrival.co"
paths:
  /users/{USER_ID}/tasks/complete-scan-data-matrix:
    post:
      parameters:
      - name: "USER_ID"
        in: "path"
        required: true
        example: "3f37ddfe-d253-46fc-92f2-0a376eed0c7b"
      - name: "Accept"
        in: "header"
        example: "*/*"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
      responses:
        "404":
          content:
            application/json: {}
